<?php

namespace Database\Seeders;

use App\Models\License;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        User::truncate();
        License::truncate();

        $users = array(
            array('id' => '1', 'name' => NULL, 'type' => 'admin', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '000', 'id_end' => NULL, 'phone' => '000', 'phone_verify_at' => NULL, 'email' => 'admin@admin.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => NULL, 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$bs0U57lseQuTpMDhiIoqZe0mUKmfIoIiZoSbLCnqz1KVX0m5Ivh6W', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-10-05 13:13:41', 'updated_at' => '2022-10-05 13:13:41', 'last_seen' => NULL, 'is_block' => NULL),
            array('id' => '2', 'name' => NULL, 'type' => 'admin', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '666', 'id_end' => NULL, 'phone' => '666', 'phone_verify_at' => NULL, 'email' => 'a1@m.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => NULL, 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$X8Z7N3lStLJ0gBjjg6Ee.esFJfB8O.jnpTTMOr2PUxZIaVPCP1WdC', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-10-05 13:13:41', 'updated_at' => '2022-10-05 13:13:41', 'last_seen' => NULL, 'is_block' => NULL,),
            array('id' => '3', 'name' => 'عميل فردي عميل عميل', 'type' => 'client', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '111', 'id_end' => NULL, 'phone' => '111', 'phone_verify_at' => NULL, 'email' => 'a1@a.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => NULL, 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$bs0U57lseQuTpMDhiIoqZe0mUKmfIoIiZoSbLCnqz1KVX0m5Ivh6W', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => '1000000', 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-10-05 13:13:41', 'updated_at' => '2022-10-05 13:13:41', 'last_seen' => NULL, 'is_block' => NULL),
            array('id' => '4', 'name' => 'عميل شركة عميل عميل', 'type' => 'client', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '222', 'id_end' => NULL, 'phone' => '222', 'phone_verify_at' => NULL, 'email' => 'a2@a.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => NULL, 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$bs0U57lseQuTpMDhiIoqZe0mUKmfIoIiZoSbLCnqz1KVX0m5Ivh6W', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-10-05 13:13:41', 'updated_at' => '2022-10-05 13:13:41', 'last_seen' => NULL, 'is_block' => NULL),
            array('id' => '5', 'name' => 'محامي فردي محامي محامي', 'type' => 'vendor', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '333', 'id_end' => NULL, 'phone' => '333', 'phone_verify_at' => NULL, 'email' => 'm1@m.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => NULL, 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$bs0U57lseQuTpMDhiIoqZe0mUKmfIoIiZoSbLCnqz1KVX0m5Ivh6W', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-10-05 13:13:41', 'updated_at' => '2022-10-05 13:13:41', 'last_seen' => NULL, 'is_block' => NULL),
            array('id' => '6', 'name' => 'محامي شركة محامي محامي', 'type' => 'vendor', 'membership' => 'company', 'gender' => 'male', 'id_number' => '444', 'id_end' => NULL, 'phone' => '444', 'phone_verify_at' => NULL, 'email' => 'm2@m.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => NULL, 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$bs0U57lseQuTpMDhiIoqZe0mUKmfIoIiZoSbLCnqz1KVX0m5Ivh6W', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-10-05 13:13:41', 'updated_at' => '2022-10-05 13:13:41', 'last_seen' => NULL, 'is_block' => NULL),
            array('id' => '7', 'name' => 'محكم محكم محكم', 'type' => 'judger', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '555', 'id_end' => NULL, 'phone' => '555', 'phone_verify_at' => NULL, 'email' => 'j1@j.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => NULL, 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$bs0U57lseQuTpMDhiIoqZe0mUKmfIoIiZoSbLCnqz1KVX0m5Ivh6W', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-10-05 13:13:41', 'updated_at' => '2022-10-05 13:13:41', 'last_seen' => NULL, 'is_block' => NULL),
            array('id' => '8', 'name' => 'محكم 222', 'type' => 'judger', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '777', 'id_end' => NULL, 'phone' => '777', 'phone_verify_at' => NULL, 'email' => 'j2@j.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => NULL, 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$bs0U57lseQuTpMDhiIoqZe0mUKmfIoIiZoSbLCnqz1KVX0m5Ivh6W', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-10-05 13:13:41', 'updated_at' => '2022-10-05 13:13:41', 'last_seen' => NULL, 'is_block' => NULL),
            array('id' => '54', 'name' => 'يزن بن علي بن حسن المالكي', 'type' => 'vendor', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '1107296848', 'id_end' => '2023-12-27', 'phone' => '0509044057', 'phone_verify_at' => NULL, 'email' => NULL, 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => NULL, 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => NULL, 'birthdate' => '1999-09-20', 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-11-03 14:24:33', 'updated_at' => '2022-11-03 14:29:54', 'last_seen' => '2022-11-03 14:29:54', 'is_block' => NULL),
            array('id' => '55', 'name' => 'محمد بن خالد الشريمي', 'type' => 'vendor', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '1059116218', 'id_end' => '2030-12-27', 'phone' => '0552134449', 'phone_verify_at' => NULL, 'email' => 'mohash26@gmailcom', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => '2', 'city_name' => NULL, 'country_id' => NULL, 'occupation_id' => '10', 'qualification_id' => '8', 'specialty_id' => '8', 'password' => NULL, 'birthdate' => '1988-11-29', 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => '7', 'bank_account' => '4780000446608010180026', 'bio' => 'أعمل ضمن فريق عمل مكتب المحامي سلمان بن عبدالله المهيني، ومهامي في المكتب القيام بإدارة فريق العمل من بدء التفاوض مع العميل ودراسة القضايا وتقديم الاستشارات الملائمة.
          كما أني متخصص في القضايا المالية والعقارية والتجارية.', 'remember_token' => NULL, 'created_at' => '2022-11-04 00:22:44', 'updated_at' => '2022-11-04 00:26:51', 'last_seen' => '2022-11-04 00:26:51', 'is_block' => NULL),
            array('id' => '56', 'name' => 'SALEH H AL SHMRANI', 'type' => 'client', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '1036630325', 'id_end' => NULL, 'phone' => '0500876876', 'phone_verify_at' => NULL, 'email' => 'admin4@admin.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => '19', 'city_name' => NULL, 'country_id' => '1', 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$VyGNDO2.72mKodd9E2fAiuJWl.E46i3VNRT8IOV7ln9u0nUqMBkj2', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-11-13 06:46:30', 'updated_at' => '2022-11-13 06:56:17', 'last_seen' => '2022-11-13 06:56:17', 'is_block' => NULL),
            array('id' => '58', 'name' => 'ddddd', 'type' => 'judger', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '3333333333', 'id_end' => NULL, 'phone' => '3333333333', 'phone_verify_at' => NULL, 'email' => 'admin77@admin.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => '19', 'city_name' => NULL, 'country_id' => '1', 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$.7jRK.YY1vrGNtyLP0ckKeKfc6nha8GwClOOulDw221fqAcf94hDK', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-11-13 06:52:08', 'updated_at' => '2022-11-13 06:52:08', 'last_seen' => NULL, 'is_block' => NULL),
            array('id' => '59', 'name' => 'dssss', 'type' => 'judger', 'membership' => 'individual', 'gender' => 'male', 'id_number' => '2222222222', 'id_end' => NULL, 'phone' => '2222222222', 'phone_verify_at' => NULL, 'email' => 'admin88@admin.com', 'email_verified_at' => NULL, 'photo' => NULL, 'city_id' => '19', 'city_name' => NULL, 'country_id' => '1', 'occupation_id' => NULL, 'qualification_id' => NULL, 'specialty_id' => NULL, 'password' => '$2y$10$odbPP7Ogu9UuF.RdqypmfudffxSCA/IKjqAzoQr7xO98AZ55vuWNa', 'birthdate' => NULL, 'address' => NULL, 'company_name' => NULL, 'company_number' => NULL, 'contract' => NULL, 'is_active' => '1', 'notes' => NULL, 'current_balance' => NULL, 'suspended_balance' => NULL, 'years_of_experience' => NULL, 'bank_account' => NULL, 'bio' => NULL, 'remember_token' => NULL, 'created_at' => '2022-11-13 06:52:42', 'updated_at' => '2022-11-13 06:53:33', 'last_seen' => NULL, 'is_block' => NULL),
            array('id' => '60','type' => 'vendor','membership' => 'individual','name' => 'عبدالمجيد','gender' => NULL,'id_number' => '1003489059','id_end' => '2022-11-14','phone' => '0563133208','phone_verify_at' => NULL,'email' => 'aaaa@aaaacomsa','email_verified_at' => NULL,'photo' => 'users/1668447105WhatsApp Image 2022-11-14 at 8.30.58 PM.jpeg','city_name' => NULL,'city_id' => '2','country_id' => NULL,'occupation_id' => '10','qualification_id' => '1','specialty_id' => '7','password' => NULL,'birthdate' => '2022-11-14','address' => NULL,'company_name' => NULL,'company_number' => NULL,'contract' => NULL,'is_active' => '1','notes' => NULL,'current_balance' => NULL,'suspended_balance' => NULL,'years_of_experience' => '23','bank_account' => '3680000448608010004554','bio' => 'محامي مُرخص منذ عام 1421هـ , عضو اساسي لدى  الهيئة السعودية للمحامين ’ مهتم لنشر الوعي القانوني.','remember_token' => NULL,'created_at' => '2022-11-14 17:27:47','updated_at' => '2022-12-06 16:44:39','last_seen' => '2022-12-06 16:44:39','is_block' => NULL),
          array('id' => '61','type' => 'vendor','membership' => 'individual','name' => 'هشام بن عبدالله بن وكيل الشيخ','gender' => 'male','id_number' => '1070209166','id_end' => '2031-12-17','phone' => '0551833028','phone_verify_at' => NULL,'email' => 't@t','email_verified_at' => NULL,'photo' => NULL,'city_name' => NULL,'city_id' => '2','country_id' => NULL,'occupation_id' => '10','qualification_id' => '8','specialty_id' => '7','password' => NULL,'birthdate' => '1988-05-09','address' => NULL,'company_name' => NULL,'company_number' => NULL,'contract' => NULL,'is_active' => '1','notes' => NULL,'current_balance' => NULL,'suspended_balance' => NULL,'years_of_experience' => '7','bank_account' => NULL,'bio' => '……','remember_token' => NULL,'created_at' => '2022-11-17 21:41:54','updated_at' => '2022-11-17 21:45:36','last_seen' => '2022-11-17 21:45:36','is_block' => NULL),
          array('id' => '62','type' => 'vendor','membership' => 'individual','name' => 'عبدالله بن متعب بن جزاء الحربي','gender' => 'male','id_number' => '1067885879','id_end' => '2029-06-19','phone' => '0505934101','phone_verify_at' => NULL,'email' => 'lawyer43372@gmailcom','email_verified_at' => NULL,'photo' => NULL,'city_name' => NULL,'city_id' => '2','country_id' => NULL,'occupation_id' => '10','qualification_id' => '9','specialty_id' => '3','password' => NULL,'birthdate' => '1971-09-02','address' => NULL,'company_name' => NULL,'company_number' => NULL,'contract' => NULL,'is_active' => '1','notes' => NULL,'current_balance' => NULL,'suspended_balance' => NULL,'years_of_experience' => '2','bank_account' => '0980000473608010022414','bio' => 'محامي ممارس في القضايا الجنائية والتجارية والعمالية والأحوال الشخصية وتأسيس الشركات والمؤسسات وجميع التراخيص الحكومية والخاصة','remember_token' => NULL,'created_at' => '2022-11-18 11:30:14','updated_at' => '2022-11-18 11:35:38','last_seen' => '2022-11-18 11:35:38','is_block' => NULL),
          array('id' => '64','type' => 'vendor','membership' => 'individual','name' => 'عبدالعزيز بن عبدالله بن بركي المطيري','gender' => 'male','id_number' => '1082405000','id_end' => '2023-10-24','phone' => '0542055522','phone_verify_at' => NULL,'email' => 'abdulazizalshlahi92@gmailcom','email_verified_at' => NULL,'photo' => NULL,'city_name' => NULL,'city_id' => '2','country_id' => NULL,'occupation_id' => '10','qualification_id' => '8','specialty_id' => '7','password' => NULL,'birthdate' => '1992-10-12','address' => NULL,'company_name' => NULL,'company_number' => NULL,'contract' => NULL,'is_active' => '1','notes' => NULL,'current_balance' => NULL,'suspended_balance' => NULL,'years_of_experience' => '5','bank_account' => NULL,'bio' => NULL,'remember_token' => NULL,'created_at' => '2022-12-01 17:51:31','updated_at' => '2022-12-01 17:53:10','last_seen' => '2022-12-01 17:53:10','is_block' => NULL),
          array('id' => '65','type' => 'vendor','membership' => 'individual','name' => 'عبدالرحمن بن مساعد بن مناجي العتيبي','gender' => 'male','id_number' => '1092478948','id_end' => '2026-09-21','phone' => '0547074676','phone_verify_at' => NULL,'email' => 'msr055@hotmailcom','email_verified_at' => NULL,'photo' => NULL,'city_name' => NULL,'city_id' => '2','country_id' => NULL,'occupation_id' => '10','qualification_id' => '7','specialty_id' => '7','password' => NULL,'birthdate' => '1996-07-08','address' => NULL,'company_name' => NULL,'company_number' => NULL,'contract' => NULL,'is_active' => '1','notes' => NULL,'current_balance' => NULL,'suspended_balance' => NULL,'years_of_experience' => '5','bank_account' => NULL,'bio' => NULL,'remember_token' => NULL,'created_at' => '2022-12-13 09:21:12','updated_at' => '2022-12-13 09:34:02','last_seen' => '2022-12-13 09:34:02','is_block' => NULL)
        );
        foreach ($users as $user) {
            User::create($user);
        }


        $licenses = array(
            array('id' => '1','name' => '888','file' => 'licenses/1665841818صورة.webp','user_id' => '8','end_at' => now()->addMonth(1),'status' => 'accepted','refused_msg' => NULL,'created_at' => '2022-10-15 13:50:18','updated_at' => '2022-10-15 14:03:27'),
            array('id' => '27','name' => '4404082','file' => 'license/1667485473شهادة المحاماة.pdf','user_id' => '54','end_at' => '2025-08-08','status' => 'pending','refused_msg' => NULL,'created_at' => '2022-11-03 14:24:33','updated_at' => '2022-11-03 14:24:33'),
            array('id' => '28','name' => '41234','file' => 'license/1667521364ترخيص المحاماة.pdf','user_id' => '55','end_at' => '2024-09-23','status' => 'accepted','refused_msg' => NULL,'created_at' => '2022-11-04 00:22:44','updated_at' => '2022-11-08 13:11:43'),
            array('id' => '30','name' => '111','file' => 'licenses/1668429378env3.png','user_id' => '5','end_at' => now()->addMonth(1),'status' => 'accepted','refused_msg' => NULL,'created_at' => '2022-11-14 12:36:18','updated_at' => '2022-11-14 12:37:15'),
            array('id' => '31','name' => '1111','file' => 'licenses/1668429545Screenshot 2022-11-10 180520.png','user_id' => '7','end_at' => now()->addMonth(1),'status' => 'accepted','refused_msg' => NULL,'created_at' => '2022-11-14 12:39:05','updated_at' => '2022-11-14 12:39:26'),
            array('id' => '33','name' => '3397','file' => 'license/1668446867الترخيص-2022.png','user_id' => '60','end_at' => '2026-10-04','status' => 'accepted','refused_msg' => NULL,'created_at' => '2022-11-14 17:27:47','updated_at' => '2022-12-13 08:20:44'),
            array('id' => '34','name' => '38314','file' => 'license/1668721314شركة هشام الشيخ للمحاماة والاستشارات القانونية-ترخيص المحاماة.pdf','user_id' => '61','end_at' => '2026-12-09','status' => 'accepted','refused_msg' => NULL,'created_at' => '2022-11-17 21:41:54','updated_at' => '2022-11-17 21:45:12'),
            array('id' => '35','name' => '43372','file' => 'license/1668771014646AC23A-5E7E-47BF-8E5D-2B5AD356BD4B.jpeg','user_id' => '62','end_at' => '2026-09-22','status' => 'accepted','refused_msg' => NULL,'created_at' => '2022-11-18 11:30:14','updated_at' => '2022-11-19 09:32:55'),
            array('id' => '36','name' => '122545','file' => 'license/1668858987555.jpg','user_id' => '63','end_at' => '2022-12-02','status' => 'pending','refused_msg' => NULL,'created_at' => '2022-11-19 11:56:27','updated_at' => '2022-11-19 11:56:27'),
            array('id' => '37','name' => '421597','file' => 'license/1669917091A3A971A5-24DE-4721-9788-3E89EF32E886.jpeg','user_id' => '64','end_at' => '2025-12-01','status' => 'accepted','refused_msg' => NULL,'created_at' => '2022-12-01 17:51:31','updated_at' => '2022-12-04 17:05:17'),
            array('id' => '38','name' => '44332','file' => 'license/1670923272ترخيص المحاماة ( عبدالرحمن ).pdf','user_id' => '65','end_at' => '2027-07-14','status' => 'accepted','refused_msg' => NULL,'created_at' => '2022-12-13 09:21:12','updated_at' => '2022-12-22 10:52:34')


          );
        

        foreach ($licenses as $l) {
            License::create($l);
        }

    }
}
